### ISSUE TITLE
Tag was lost on Xperia Z2 and Z3

### ISSUE THREAD

**Issue by blacasa** [chariotsolutions/phonegap-nfc#167]
Hi,

I use your plugin to write NFCV tags. It works well with some phones (Sony Xperia Z, Z1, and Samsung GS3), but it doesn't works with Sony Xperia Z2, and Xperia Z3.
On reading tag, I have the error mesage "Tag was lost".

Have you any idea on what could be the problem?

Thanks

**Comment by don** [comment]
@blacasa I haven't used NFCV tags, but have found that some tags, particularly NFC Forum Type 4 tags are slow on older Android devices. Maybe that's the issue here?

Try reading with [NFC TagInfo by NXP](https://play.google.com/store/apps/details?id=com.nxp.taginfolite&hl=en) to ensure the tags work with your device.
