### ISSUE TITLE
READ RECORDED VALUES

### ISSUE THREAD

**Issue by jomego** [chariotsolutions/phonegap-nfc#412]
Very good, I am trying something very simple ... I have a text stored on an NFC card and what I want is to read the value and pass it to a variable ...

I am using cordova on Android:

nfc.readerMode (
     nfc.FLAG_READER_NFC_A | nfc.FLAG_READER_NO_PLATFORM_SOUNDS,
     nfcTag => console.log (JSON.stringify (nfcTag)),
     error => console.log ('NFC reader mode failed', error)
);

but I can't find my phrase anywhere ... how could I read it.

Thanks in advance

**Comment by don** [comment]
The data from the NFC tag is passed to the Promise when it is resolved. In your case this is ` nfcTag => console.log (JSON.stringify (nfcTag))`. If you look at the console output you should see JavaScript representing that NFC data on the tag. You'll need to get the payload field from the ndefMessage array in the nfcTag and decode the data. The format of the data looks like this https://github.com/chariotsolutions/phonegap-nfc#nfcreadermode

There are some helper functions in phonegap-nfc.js. You might be able to use [bytesToString](https://github.com/chariotsolutions/phonegap-nfc/blob/a3b1e3ad5c11267aa3a8468519b4bb7e4d84800a/www/phonegap-nfc.js#L617) or [decodeMessage](https://github.com/chariotsolutions/phonegap-nfc/blob/a3b1e3ad5c11267aa3a8468519b4bb7e4d84800a/www/phonegap-nfc.js#L273). The plugin gets the bytes from the tag. You need to look at the TNF and type in order to know how to decode the payload.
